export const LOCATIONS = [
  {
    district: 'Nairobi West',
    division: 'Dagoretti',
    location: 'Kawangware',
    subLocation: 'Gatina',
  },
  {
    district: 'Westlands',
    division: 'Westlands',
    location: 'Kilimani',
    subLocation: 'Maziwa',
  },
  {
    district: 'Nairobi East',
    division: 'Embakasi',
    location: 'Njiru',
    subLocation: 'Njiru',
  },
  {
    district: 'Nairobi East',
    division: 'Makadara',
    location: 'Maringo',
    subLocation: 'Mbotela',
  },
  {
    district: 'Kiambaa',
    division: 'Kiambaa',
    location: 'Kihara',
    subLocation: 'Mahindi',
  },
  {
    district: 'Kikuyu',
    division: 'Kabete',
    location: 'Muguga',
    subLocation: 'Kahuho',
  },
  {
    district: 'Lari',
    division: 'Gatamaiyu',
    location: 'Kamburu',
    subLocation: 'Kagaa',
  },
  {
    district: 'Thika East',
    division: 'Kakuzi',
    location: 'Ngelela',
    subLocation: 'Magumo',
  },
  {
    district: 'Taita',
    division: 'Wundanyi',
    location: 'Wumingu',
    subLocation: 'Mwarungu',
  },
  {
    district: 'Taveta',
    division: 'Bomeni',
    location: 'Kitobo',
    subLocation: 'Mrabani',
  },
  {
    district: 'Kilindini',
    division: 'Jomvi',
    location: 'Mikindani',
    subLocation: 'Kwashee',
  },
  {
    district: 'Mombasa',
    division: 'Kisauni',
    location: 'Kongowea',
    subLocation: 'Maweni',
  },
  {
    district: 'Kaloleni',
    division: 'Rabai',
    location: 'Ruruma',
    subLocation: 'Mleji',
  },
  {
    district: 'Malindi',
    division: 'Marafa',
    location: 'Garashi',
    subLocation: 'Sigwaya',
  },
  {
    district: 'Kilifi',
    division: 'Vitengeni',
    location: 'Sokoke',
    subLocation: 'Rare',
  },
  {
    district: 'Tana Delta',
    division: 'Kipini',
    location: 'Ozi',
    subLocation: 'Mpeketoni',
  },
  {
    district: 'Tana River',
    division: 'Wenje',
    location: 'Mazuni',
    subLocation: 'Mkomani',
  },
];
